name: GitHub Repo Search

on:
  workflow_dispatch:
    inputs:
      keywords:
        description: 'Comma-separated keywords to search'
        required: true
        default: 'saas starter,saas kit,starter kit, saas boilerplate, next.js saas, react.js saas, laravel saas, starter template, b2b saas, saas kit, remix saas, saas framework,saas starter kit, next.js starter kit, react.js starter kit, laravel starter kit, remix starter kit, open source saas, saas starter template, production-ready saas, free open-source saas, node.js starter kit, saas starter framework'

jobs:
  run-search:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml python-dotenv

      - name: Run GitHub repo search script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYWORDS_ENV: ${{ github.event.inputs.keywords }}
        run: |
          python dailystarter.py

      - name: Upload search results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: search-results
          path: results/data.json
